name: Tests on GPU

on:
  push:
    branches:
      - main
    tags:
      - v*.*.*
  pull_request: {}

jobs:
  test:
    runs-on: [ubuntu-latest, gpu]

    steps:
        - name: Check out the repository
          uses: actions/checkout@v4

        - name: Install pixi
          run: |
            curl -fsSL https://pixi.sh/install.sh | bash
            echo "$HOME/.pixi/bin" >> $GITHUB_PATH

        - name: Show NVIDIA-smi
          run: nvidia-smi

        - name: install pixi test environment
          run: pixi install -e dev

        - name: run pytest
          run: pixi run -e dev test
